# TRIPLEO-CI environment settings
undercloud_user: "{{ lookup('env','USER') }}"
non_root_user: "{{ undercloud_user }}"
extra_args: >
    -e {{ tripleo_root }}/tripleo-ci/test-environments/worker-config.yaml
    -e /usr/share/openstack-tripleo-heat-templates/environments/debug.yaml
    --overcloud-ssh-user {{ undercloud_user }}

composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller

toci_vxlan_networking: true
toci_vxlan_networking_multinode: true
vxlan_mtu: 1350
hostname_correction: true # workaround restriction on toci images

# environment settings, not TRIPLEO-CI specific
undercloud_local_interface: "br-ex" # related to osinfra network configuration
flavor_args: ""
undercloud_conf_extras: "net_config_override = /opt/stack/new/tripleo-ci/undercloud-configs/net-config-multinode.json.template"
generate_pingtest_subunit: true
# Images settings
image_cache_dir_cleanup: true
# user home (working_dir default) is the base dir for all images operations
# if it's changed, nothing will work
build_image_isolated: false
build_undercloud: false

# We don't need to cleanup TripleO CI
tempest_track_resources: false

# Container settings
docker_registry_host: trunk.registry.rdoproject.org
docker_registry_namespace: "{{ release }}"

