# TRIPLEO-CI environment settings
undercloud_user: "{{ lookup('env','USER') }}"
non_root_user: "{{ undercloud_user }}"
ssh_user: "{{ undercloud_user }}"
workers_args: >-
    -e {{ overcloud_templates_path }}/environments/low-memory-usage.yaml
    -e {{ tripleo_root }}/tripleo-ci/test-environments/worker-config.yaml
    -e {{ overcloud_templates_path }}/environments/debug.yaml
# undercloud deployment
undercloud_docker_registry_mirror: "{{ lookup('env','NODEPOOL_DOCKER_REGISTRY_PROXY') }}"

dlrn_use_local_mirrors: true

vxlan_networking: true
hostname_correction: true # workaround restriction on toci images

# environment settings, not TRIPLEO-CI specific
undercloud_local_interface: "br-ex" # related to osinfra network configuration
flavor_args: ""
undercloud_conf_extras: "net_config_override = /opt/stack/new/tripleo-ci/undercloud-configs/net-config-multinode.json.template"
generate_pingtest_subunit: true
undercloud_undercloud_nameservers:
  - 127.0.0.1
tempest_test_image_path: /opt/cache/files/cirros-0.3.5-x86_64-disk.img

# We don't need to cleanup TripleO CI
tempest_track_resources: false

#build-test packages
artg_repos_dir: /home/zuul/src/git.openstack.org/openstack

