# This file contains settings that are specific to RDO Cloud.
# These settings will override the ovb default settings

bmc_flavor: ci.m1.small
baremetal_flavor: ci.m1.xlarge
undercloud_flavor: ci.m1.xlarge

custom_nameserver:
    - 38.145.33.91
    - 38.145.32.66
    - 38.145.32.79
undercloud_undercloud_nameservers: "{{ custom_nameserver }}"
external_net: '38.145.32.0/22'
overcloud_dns_servers: "{{ custom_nameserver }}"
ntp_server: 'pool.ntp.org'
workers_args: >-
    -e {{ overcloud_templates_path }}/environments/low-memory-usage.yaml
    -e {{ tripleo_root }}/tripleo-ci/test-environments/worker-config.yaml
    -e {{ overcloud_templates_path }}/environments/debug.yaml
overcloud_image_url: http://images.rdoproject.org/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/overcloud-full.tar
ipa_image_url: http://images.rdoproject.org/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/ironic-python-agent.tar
docker_registry_host: trunk.registry.rdoproject.org
docker_registry_namespace: "{{ release }}"

# We don't need to cleanup TripleO CI
tempest_track_resources: false

# Tempestmail settings
tempestmail_log_server: http://logs.rdoproject.org
