undercloud_user: "{{ lookup('env','USER') }}"
non_root_user: "{{ undercloud_user }}"
ssh_user: "{{ undercloud_user }}"
enable_vbmc: false
gating_repo_enabled: true

workers_args: >-
    -e {{ overcloud_templates_path }}/environments/low-memory-usage.yaml
    -e {{ tripleo_root }}/tripleo-ci/test-environments/worker-config.yaml
    -e {{ overcloud_templates_path }}/environments/debug.yaml
# Undercloud setup
undercloud_ironic_ipxe_port: 3816
non_root_user_setup: false
step_set_undercloud_hostname: true
undercloud_hostname: undercloud
undercloud_docker_registry_mirror: "{{ lookup('env','NODEPOOL_DOCKER_REGISTRY_PROXY') }}"

skip_pingtest_cleanup: true
# Overcloud deploy
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates

# Network
# Deploy args
flavor_args: ""

deploy_timeout: 110

# Images settings
image_cache_dir: "{{ working_dir }}/images-cache"
image_cache_dir_cleanup: true
# user home (working_dir default) is the base dir for all images operations
# if it's changed, nothing will work
images_working_dir: "{{ working_dir }}"
build_image_isolated: false
build_undercloud: false
images_destroy_working_dir: false
libguestfs_mode: false
generate_pingtest_subunit: true
# Network settings
undercloud_undercloud_nameservers:
  - 127.0.0.1
  - 10.1.8.10
overcloud_dns_servers:
  - 10.1.8.10
  - 8.8.8.8
  - 8.8.4.4
step_adjust_mtu: true
mtu: 1350
host_network_interfaces:
  - eth0
  - eth1
  - "{% if network_isolation|default(true)|bool %}eth2{% endif %}"
mtu_interface: "{{ host_network_interfaces|select()|list }}"
undercloud_local_mtu: 1350
overcloud_neutron_global_physnet_mtu: 1350
floating_ip_cidr: >-
  {%- if network_isolation|default(true)|bool %}10.0.0.0/24
  {%- else %}192.168.24.0/24
  {%- endif %}
tempest_test_image_path: /opt/cache/files/cirros-0.3.5-x86_64-disk.img
overcloud_image_url: http://192.168.103.253/builds-{{ release }}/current-tripleo/overcloud-full.tar
ipa_image_url: http://192.168.103.253/builds-{{ release }}/current-tripleo/ipa_images.tar

# We don't need to cleanup TripleO CI
tempest_track_resources: false

# Deployment metrics
ara_graphite_prefix: "test.tripleo.{{ lookup('env', 'STABLE_RELEASE')|default('master', true) }}.{{ lookup('env', 'TOCI_JOBTYPE') }}."
ara_graphite_server: 66.187.229.172
