---

- job:
    name: tripleo-ci-dsvm
    description: |
      Base job template for TripleO jobs that leverage devstack-gate/dsvm
    parent: legacy-dsvm-base
    pre-run: playbooks/nodepool-provider/pre.yaml
    vars:
      # Note (dmsimard): This enforces a minimum TTL for DNS records, see
      # https://review.openstack.org/#/c/523178/ for context
      unbound_cache_min_ttl: 900
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/tripleo-ci
      - openstack/tripleo-quickstart
      - openstack/tripleo-quickstart-extras
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^spec/.*$
      - ^Puppetfile.*$
      - tox.ini
      - ^setup.*$

- job:
    name: tripleo-ci-dsvm-multinode
    description: |
      Base legacy job for multinode tripleo jobs.

      Ensures the firewall allows all traffic between test nodes.
    parent: tripleo-ci-dsvm
    roles:
      - zuul: openstack-infra/zuul-jobs
    pre-run: playbooks/multinode-networking/pre.yaml
